'.\" t
.\"     Title: yara-editor
.\"    Author: Ivan Fontarensky <ivan.fontarensky_at_gmail.com>
.\"    Manual: yara-editor Manuel
.\"      Date: 2011-08-18
.\"  Language: French
.\"
.TH "YARA-EDITOR" "8" "2012\-07\-04" "YARA-EDITOR 3\&.0\&.6\" YARA-EDITOR" Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH NAME
YARA-EDITOR
.SH SYNOPSIS
.sp
\fIyara-editor\fR <file>
.sp
.SH "DESCRIPTION"
.sp
YARA-EDITOR - just an editor for yara rules\&
.RE
.SH OPTIONS
.RE
.PP
	\fB\-h, \-\-help\fR
.RS 4
Display help and exit\&.
.RE
.PP
	\fB\-v, \-\-verbose\fR
.RS 4
Verbose mode enable
.RE
.PP
	\fB\-V, \-\-version\fR
.RS 4
Display version and exit\&.
.RE
.SH BUGS
.sp
http://code.google.com/p/yara-editor/
.SH AUTEURS
.sp
Developer: Ivan Fontarensky <ivan.fontarensky_at_gmail.com>
.sp
Manual: Ivan Fontarensky <ivan.fontarensky_at_gmail.com>
